### ISSUE TITLE
Clarity with TIFF formatting

### ISSUE THREAD

**Issue by DippedPretzels** [GuillaumeMougeot/biom3d#3]
Looking at the docs: 

> 
> The images and masks must all have 3 or 4 dimensions: (height, width, depth) or (channel, height, width, depth).
> 
> Each dimension of each image must be identical to each dimension of the corresponding mask, expect for the channel dimension.
> 
> Masks values must be either 0 or 1 if stored in (channel, height, width, depth) format, or must be in 0,1,…,N where N is the number of classes.

So if I have a multi-class mask TIFF, the TIFF should be formatted CXYZ? I can't find a way in ImageJ or Imaris to export this way (mostly XYZCT or XYZTC) - is this possible in Slicer or SimpleITK? 

And for masks, if this was an 8bit image, when you say values must be 0 or 1, do you mean "0"/"1", or "0"/"255"?

**Comment by GuillaumeMougeot** [comment]
Hi @DippedPretzels,

I added an ImageJ TIFF reader in biom3d so the data formatted should automatically be detected. It can be in any order as biom3d will read the metadata of the ImageJ image and re-order it automatically. 

For the masks, if you have multi-classes, by default biom3d is configured for masks formatted with voxel values of 0, 1, 2, etc... but if you have 0, 255 this should also be automatically by biom3d and adapted also automatically. 

Give it a try, and if biom3d gives you an error please don't hesitate to update this issue.

Guillaume

**Comment by DippedPretzels** [comment]
Hi Guillaume,

Ah cool - ImageJ reader is nice, but this part still confuses me:

> For the masks, if you have multi-classes, by default biom3d is configured for masks formatted with voxel values of 0, 1, 2, etc... but if you have 0, 255 this should also be automatically by biom3d and adapted also automatically.

So for a 3 class, 8bit mask, are you saying that you will have an XYZ image (1 channel), and any given voxel should have the value 0, 1, or 2? (So theoretical max number of classes would be 256 for an 8bit mask)

Or are you saying you should have a 3 channel (0, 1, 2) XYZ image, and in each channel, any given voxel should have the value [0 or 1] or [0 or 255]?

Thanks

**Comment by GuillaumeMougeot** [comment]
Dear @DippedPretzels ,

Yes, what you stated here is correct:

> So for a 3 class, 8bit mask, are you saying that you will have an XYZ image (1 channel), and any given voxel should have the value 0, 1, or 2? (So theoretical max number of classes would be 256 for an 8bit mask)

Guillaume

**Comment by DippedPretzels** [comment]
Awesome - thanks!  I'll try it out.
