### ISSUE TITLE
Empty foreground when preprocessing

### ISSUE THREAD

**Issue by kelachan** [GuillaumeMougeot/biom3d#5]
I have a 16-bit mask TIFF with one channel, 2 classes (voxel values [0 1 2]) and an accompanying 16-bit image TIFF. However, when I go through the preprocessing step, I encounter the following warnings:

![image](https://github.com/GuillaumeMougeot/biom3d/assets/48563229/af39aebb-69a7-4887-b1ca-8b9109e72cd4)

For reference, [here](https://www.dropbox.com/scl/fi/x82zwn7fh03k74c9dpqvw/example_mask.tif?rlkey=cwbxtce11bn6rxfrndo7wsn0z&st=w58a8zgq&dl=0) is an example of the mask TIFF I am using.
Any help would be appreciated!

**Comment by GuillaumeMougeot** [comment]
Hi,
I tried to open your file in napari and in ImageJ and in both cases it was empty.
![image](https://github.com/GuillaumeMougeot/biom3d/assets/23736180/aaea9100-5a97-422b-8088-8dacf4adce06)
![image](https://github.com/GuillaumeMougeot/biom3d/assets/23736180/81467232-8348-46ec-9a2f-6181ce40d21d)

**Comment by kelachan** [comment]
So sorry - I was using the wrong TIFF file there. This is the correct dialogue from the console:
![image](https://github.com/GuillaumeMougeot/biom3d/assets/48563229/f2c033d8-c227-4692-80eb-4e737ab8656d)

And [here](https://www.dropbox.com/scl/fi/x82zwn7fh03k74c9dpqvw/example_mask01.tif?rlkey=cwbxtce11bn6rxfrndo7wsn0z&st=65mwz19p&dl=0) is a mask file that should work.

**Comment by GuillaumeMougeot** [comment]
I cannot reproduce your error. Are you trying that with the latest version of biom3d 0.0.38? Here is what I obtained:
![image](https://github.com/GuillaumeMougeot/biom3d/assets/23736180/bbf0a854-2580-4402-a71e-320770a6b05f)

**Comment by kelachan** [comment]
Yes, I am trying with the latest version. Here are full resolution (2000x1000) [image](https://www.dropbox.com/scl/fi/hyb647z082fz1dywpuvjn/example_image_2000.tif?rlkey=zgwwqn3upr785kdeqpiha450q&st=ypsubqfz&dl=0) and [mask](https://www.dropbox.com/scl/fi/20dwizxwttg6mcthro7t2/example_mask_2000.tif?rlkey=k3zz234278t4k55gy32bhyp0o&st=dwp63pbu&dl=0) files. Interestingly enough, it seems to be only at this resolution that I receive this error - at 1500x750 and 500x250 both, autoconfiguration runs smoothly.
However, if I run the training and prediction on these lower resolution files, the prediction tiff (a duplicate of the image file) is always empty.

**Comment by GuillaumeMougeot** [comment]
it seems that you are not using the latest version because in your screenshot, line 218 of auto_config.py file is not what you get in the latest version. Could you try to run:  `pip install -U biom3d` in your terminal/environment, then retry, and post your terminal print?
Using your images I also found another strange behavior of biom3d regarding data normailzation. I am fixing that ASAP.

**Comment by GuillaumeMougeot** [comment]
Hi I fixed the preprocessing normally. Could you try to use the latest version of biom3d? 

to update: `pip install -U biom3d`

to check if you have the latest version: `pip show biom3d` and it should display 0.0.39

**Comment by kelachan** [comment]
![image](https://github.com/GuillaumeMougeot/biom3d/assets/48563229/1ae628af-5643-4527-8d08-02f4cd578ae7)
Thank you, that worked! I am running the predictions and will let you know what it outputs on my end.

**Comment by kelachan** [comment]
I was able to get some predictions! Thank you very much for all your help!
