### ISSUE TITLE
error when trying pip install biom3d[gui]

### ISSUE THREAD

**Issue by pawlowska** [GuillaumeMougeot/biom3d#7]
I am able to install biom3d with pip, but I get an error for biom3d[gui]. I'm using Windows 10. 

Here is the terminal output:

`Logger.cpp
      src/ice/cpp/include\IceUtil/Timer.h(105): error C2039: 'binary_function': is not a member of 'std'
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include\set(23): note: see declaration of 'std'
      src/ice/cpp/include\IceUtil/Timer.h(105): error C2504: 'binary_function': base class undefined
      src/ice/cpp/include\IceUtil/Timer.h(105): error C2143: syntax error: missing ',' before '<'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]`

`  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for zeroc-ice
  Running setup.py clean for zeroc-ice
Failed to build zeroc-ice
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (zeroc-ice)`

**Comment by GuillaumeMougeot** [comment]
hi,
the installation of `pip install biom3d[gui]` is only necessary if you intend to use OMERO. Otherwise you do not need it to start the GUI.
if you do need OMERO, please refer to the documentation here: https://biom3d.readthedocs.io/en/latest/installation.html#python-virtual-environment
and this quote:

> Warning: For Windows users: you might need to install [Visual Studio C++ 14.0](https://stackoverflow.com/questions/29846087/error-microsoft-visual-c-14-0-is-required-unable-to-find-vcvarsall-bat) to install zeroc dependency. If it does not work, please refers to the Anaconda installation.

**Comment by pawlowska** [comment]
This was not clear to me. Indeed I am able to start the GUI, so I'm happy.
(I do not currently use Omero, but I do have Visual Studio installed, as you can see from the error, it manages to compile some files and only crashes on the `Logger.cpp`)

**Comment by GuillaumeMougeot** [comment]
great, 
the error with visual studio might be related to VS installed library and might need more information to solve. a workaround is to use Anaconda instead... but it might not be need.
i will close the issue, feel free to reopen one if needed
